// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: Wed 27 Nov 2019 21:28:21 UTC

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/sabnak227/jwt-demo/resource"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC ResourceServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.ResourceServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// resource

		getresource: grpctransport.NewServer(
			endpoints.GetResourceEndpoint,
			DecodeGRPCGetResourceRequest,
			EncodeGRPCGetResourceResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the ResourceServer interface
type grpcServer struct {
	getresource grpctransport.Handler
}

// Methods for grpcServer to implement ResourceServer interface

func (s *grpcServer) GetResource(ctx context.Context, req *pb.ResourceRequest) (*pb.ResourceResponse, error) {
	_, rep, err := s.getresource.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ResourceResponse), nil
}

// Server Decode

// DecodeGRPCGetResourceRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC getresource request to a user-domain getresource request. Primarily useful in a server.
func DecodeGRPCGetResourceRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ResourceRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCGetResourceResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain getresource response to a gRPC getresource reply. Primarily useful in a server.
func EncodeGRPCGetResourceResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ResourceResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
