// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: Wed 27 Nov 2019 21:28:21 UTC

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/sabnak227/jwt-demo/users"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC UserServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.UserServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// user

		authuser: grpctransport.NewServer(
			endpoints.AuthUserEndpoint,
			DecodeGRPCAuthUserRequest,
			EncodeGRPCAuthUserResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the UserServer interface
type grpcServer struct {
	authuser grpctransport.Handler
}

// Methods for grpcServer to implement UserServer interface

func (s *grpcServer) AuthUser(ctx context.Context, req *pb.AuthUserRequest) (*pb.AuthUserResponse, error) {
	_, rep, err := s.authuser.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.AuthUserResponse), nil
}

// Server Decode

// DecodeGRPCAuthUserRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC authuser request to a user-domain authuser request. Primarily useful in a server.
func DecodeGRPCAuthUserRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.AuthUserRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCAuthUserResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain authuser response to a gRPC authuser reply. Primarily useful in a server.
func EncodeGRPCAuthUserResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.AuthUserResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
