// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: Wed 27 Nov 2019 21:28:21 UTC

// Package grpc provides a gRPC client for the User service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/sabnak227/jwt-demo/users"
	"github.com/sabnak227/jwt-demo/users/user-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.UserServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var authuserEndpoint endpoint.Endpoint
	{
		authuserEndpoint = grpctransport.NewClient(
			conn,
			"user.User",
			"AuthUser",
			EncodeGRPCAuthUserRequest,
			DecodeGRPCAuthUserResponse,
			pb.AuthUserResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		AuthUserEndpoint: authuserEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCAuthUserResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC authuser reply to a user-domain authuser response. Primarily useful in a client.
func DecodeGRPCAuthUserResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.AuthUserResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCAuthUserRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain authuser request to a gRPC authuser request. Primarily useful in a client.
func EncodeGRPCAuthUserRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.AuthUserRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
